stages:
- test
language: python
jobs:
  include:
  - stage: test
    name: Tests Python 2.7
    sudo: required
    python:
    - '2.7'
    services:
    - docker
    before_install:
    - docker pull vault:latest
    - docker ps -a
    install: pip install tox-travis
    script: tox
